<a href="https://colab.research.google.com/github/OIZHENHAU/Aerospace-Management-Project/blob/main/Group_22_Mini_Group_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mini Group Assignment 2 (Group 22)
## Member in the team:
- Oi Zhen Hau
- Tan Zhen Yu
- Jasmine Teo Gie Ming
- Soh Chang Zheng
- Tiew Yi Xu

## Operation Precog: Predictive Crime Analytics
### The Scenario
You are a team of data scientists hired by the Metropolitan Police Department of "Metropolis X". The city has recently experienced a shift in crime patterns, and the police chief wants to transition to proactive, data-driven policing. They need to understand the underlying statistical factors driving crime rates and build predictive models to allocate patrol units effectively.
The Mayor has given your team exactly 48 hours to perform statistical inference on historical crime records, test hypotheses regarding crime drivers, and develop machine learning pipelines to predict future high-risk zones.


## Provided Datasets
### You will be provided with two comprehensive datasets:
-	`crime_statistics.csv`: Contains numerical data on crime rates and various socio-economic factors (e.g., unemployment rate, average income, education level) across different districts over the past decade.
-	`patrol_logs.json`: Contains classification data detailing past patrol deployments and whether a district escalated into a "High Risk" zone (True/False) based on the recorded features.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('crime_statistics.csv')
df.head()

,District,Year,Season,Unemployment_Rate,Average_Income,Education_Level,Population_Density,Police_Presence,Crime_Rate
0,District_7,2015,Winter,3.26,32197.0,13.3,2716.0,Low,23.89
1,District_20,2019,Spring,9.24,53627.0,8.3,1715.0,High,26.58
2,District_15,2017,Fall,11.16,39358.0,12.8,2710.0,Low,54.59
3,District_11,2019,Fall,4.03,69395.0,10.3,4773.0,Low,36.30
4,District_8,2022,Fall,8.53,67099.0,12.1,1801.0,Low,46.71

In [3]:
import json

In [4]:
with open('patrol_logs.json') as f:
    data = json.load(f)


df_json = pd.DataFrame(data)
df_json.head()

,Log_ID,District,Patrol_Frequency,Emergency_Calls,Previous_Incidents,Police_Staffing,Response_Time_Avg,Public_Sentiment_Score,Lighting_Quality,Event_Density,High_Risk
0,LOG-00001,District_4,26,103,78,113,24.2,7.2,3.6,8,True
1,LOG-00002,District_18,3,144,41,61,15.2,8.4,8.0,12,True
2,LOG-00003,District_14,19,116,21,63,25.3,1.1,4.0,8,True
3,LOG-00004,District_4,21,130,13,78,29.7,3.3,1.2,10,False
4,LOG-00005,District_1,6,38,42,56,8.5,4.3,1.3,7,False